apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  selector:
    matchLabels:
      app: history
  replicas: 3
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: jinseok351/lotto-history:latest
          env:
            - name: profile
              value: "prod"
            - name: user
              value: "postgres"
            - name: password
              value: "1234"
          ports:
            - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  ports:
    - port: 8080
      nodePort: 30003
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: history-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: history
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
